version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      mui:
        patterns: ["@mui/*", "@emotion/*"]
      react:
        patterns: ["react", "react-dom", "@types/react*"]

  - package-ecosystem: "npm"
    directory: "/apps/watchlab"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      aws:
        patterns: ["@aws-sdk/*"]

  - package-ecosystem: "pip"
    directory: "/services/biograph_api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/services/biograph_api"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/apps/watchlab"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/apps/dashboard"
    schedule:
      interval: "monthly"
