"""Pydantic schemas for API requests/responses.

Re-export hub: all schema classes are defined in domain-specific sub-modules
and re-exported here so that ``from .schemas import X`` continues to work
everywhere in the codebase without any import changes.
"""

from __future__ import annotations

# -- Common / base mixins ---------------------------------------------------
from .schemas_common import (  # noqa: F401
    AU_DEFAULTS,
    TimeRangeInclusiveMixin,
    TimeRangeMixin,
    VideoTimeRangeInclusiveMixin,
)

# -- Video -------------------------------------------------------------------
from .schemas_video import (  # noqa: F401
    FeatureTrackRead,
    SceneBoundary,
    TimelineAnalysisJobResponse,
    TimelineAnalysisRequest,
    TimelineFeatureWindowResponse,
    TimelineSegmentRead,
    VideoCatalogItem,
    VideoCatalogResponse,
    VideoCatalogSession,
    VideoCreate,
    VideoCtaMarkerIn,
    VideoCtaMarkerRead,
    VideoCtaMarkersResponse,
    VideoCtaMarkersUpdateRequest,
    VideoCutIn,
    VideoCutRead,
    VideoRead,
    VideoSceneGraphResponse,
    VideoSceneIn,
    VideoSceneRead,
    VideoUpdate,
    StudyDetail,
    StudyListItem,
    StudyListResponse,
    StudyUpdate,
)

# -- Session / trace / annotation / capture ----------------------------------
from .schemas_session import (  # noqa: F401
    AnnotationMarkerType,
    ParticipantAttach,
    PlaybackTelemetryIngestRequest,
    PlaybackTelemetryIngestResponse,
    QCStats,
    QualityOverlayBucket,
    SceneMetric,
    SessionAnnotationIn,
    SessionAnnotationIngestRequest,
    SessionAnnotationIngestResponse,
    SessionAnnotationRead,
    SessionCaptureFrameIn,
    SessionCaptureFramePointerIn,
    SessionCaptureIngestRequest,
    SessionCaptureIngestResponse,
    SessionCreate,
    SessionPlaybackEventIn,
    SessionPlaybackEventRead,
    SessionRead,
    StudyCreate,
    StudyRead,
    SurveyIngestRequest,
    SurveyIngestResponse,
    SurveyResponseIn,
    SurveyResponseRead,
    TraceBucket,
    BatchSessionIngestRequest,
    BatchSessionIngestResponse,
    TraceIngestResponse,
    TracePointIn,
    VideoSummaryResponse,
)

# -- Neuro scores / diagnostics / product rollups ---------------------------
from .schemas_neuro import (  # noqa: F401
    AttentionalSynchronyDiagnostics,
    AttentionalSynchronyExtrema,
    AttentionalSynchronyPathway,
    AttentionalSynchronyTimelineScore,
    AuFrictionDiagnostics,
    AuFrictionPathway,
    AuFrictionQualityWarning,
    AuFrictionQualityWarningSeverity,
    AuFrictionState,
    AuFrictionTimelineWindow,
    BlinkTransportDiagnostics,
    BlinkTransportPathway,
    BlinkTransportTimelineScore,
    BlinkTransportWarning,
    BlinkTransportWarningSeverity,
    BoundaryEncodingDiagnostics,
    BoundaryEncodingFlag,
    BoundaryEncodingFlagSeverity,
    BoundaryEncodingPathway,
    BoundaryEncodingTimelineWindow,
    BoundaryEncodingTimelineWindowType,
    CreatorProductRollups,
    CtaReceptionDiagnostics,
    CtaReceptionFlag,
    CtaReceptionFlagSeverity,
    CtaReceptionPathway,
    CtaReceptionTimelineWindow,
    EnterpriseDecisionSupport,
    EnterpriseProductRollups,
    IncrementalityExperimentResultIn,
    LegacyScoreAdapter,
    NarrativeControlDiagnostics,
    NarrativeControlHeuristicCheck,
    NarrativeControlMomentContribution,
    NarrativeControlPathway,
    NarrativeControlSceneScore,
    NeuroCompositeRollup,
    NeuroEvidenceWindow,
    NeuroFeatureContribution,
    NeuroRollupFamilies,
    NeuroRollupMachineName,
    NeuroRollupRegistryEntry,
    NeuroScoreContract,
    NeuroScoreFamilies,
    NeuroScoreMachineName,
    NeuroScoreRegistryEntry,
    NeuroScoreStatus,
    NeuroScoreTaxonomy,
    ProductLiftComparison,
    ProductLiftTruthStatus,
    ProductRollupMode,
    ProductRollupPresentation,
    ProductRollupWarning,
    ProductRollupWarningSeverity,
    ProductScoreSummary,
    ReadoutAggregateMetrics,
    RewardAnticipationDiagnostics,
    RewardAnticipationPathway,
    RewardAnticipationTimelineWindow,
    RewardAnticipationTimelineWindowType,
    RewardAnticipationWarning,
    RewardAnticipationWarningSeverity,
    SelfRelevanceDiagnostics,
    SelfRelevancePathway,
    SelfRelevanceTimelineWindow,
    SelfRelevanceWarning,
    SelfRelevanceWarningSeverity,
    SocialTransmissionDiagnostics,
    SocialTransmissionPathway,
    SocialTransmissionTimelineWindow,
    SyntheticLiftCalibrationStateRead,
    SyntheticLiftCalibrationStatus,
    SyntheticLiftCalibrationStatusResponse,
    SyntheticLiftCalibrationSyncRequest,
    SyntheticLiftCalibrationSyncResponse,
    SyntheticLiftPriorDiagnostics,
    SyntheticLiftPriorFeatureInput,
    SyntheticLiftPriorFeatureInputSource,
    SyntheticLiftPriorPathway,
    SyntheticLiftPriorTimelineWindow,
)

# -- Readout -----------------------------------------------------------------
from .schemas_readout import (  # noqa: F401
    AnnotationSummary,
    CatalogReliabilityItem,
    CatalogReliabilityReport,
    CompactReadoutHighlights,
    CompactReadoutReport,
    MarkerDensityPoint,
    MarkerTimestampSummary,
    ReadoutAUChannel,
    ReadoutContext,
    ReadoutCut,
    ReadoutCtaMarker,
    ReadoutExportJson,
    ReadoutExportPackageResponse,
    ReadoutLabels,
    ReadoutLowConfidenceWindow,
    ReadoutPayload,
    ReadoutPreflightIssue,
    ReadoutPreflightResponse,
    ReadoutQuality,
    ReadoutQualitySummary,
    ReadoutReliabilityScore,
    ReadoutScene,
    ReadoutSegment,
    ReadoutSegments,
    ReadoutTimebase,
    ReadoutTracePoint,
    ReadoutTraces,
    ReadoutVideoMetadata,
    ReliabilityScoreDetail,
    RewardProxyPeak,
    SceneDiagnosticCard,
    SurveySummary,
    VideoReadoutResponse,
)

# -- Prediction / testing queue / analyst views ------------------------------
from .schemas_prediction import (  # noqa: F401
    AnalystSessionItem,
    AnalystSessionsResponse,
    AnalystSurveyResponseItem,
    PredictJobsObservabilityStatus,
    PredictJobStatus,
    PredictResponse,
    PredictTracePoint,
    TestingQueueAssignment,
    TestingQueueItem,
    TestingQueueResponse,
    TestingQueueSegment,
    TestingUncertaintyPoint,
)

# -- Observability / frontend diagnostics -----------------------------------
from .schemas_observability import (  # noqa: F401
    CaptureArchiveFailureCodeCount,
    CaptureArchiveObservabilityStatusResponse,
    CaptureArchivePurgeResponse,
    FrontendDiagnosticErrorCount,
    FrontendDiagnosticEventIn,
    FrontendDiagnosticEventRead,
    FrontendDiagnosticEventsResponse,
    FrontendDiagnosticSummaryResponse,
    NeuroObservabilityLatestSnapshot,
    NeuroObservabilityStatusResponse,
)
